// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://homsrlmqlkwskntcsscz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvbXNybG1xbGt3c2tudGNzc2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzY2ODEsImV4cCI6MjA3MzAxMjY4MX0.-_CYQ56bwNoqs8hVHWRg3ko3kXfqlMWGRMAtlMUBQqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});